services:
    express:
        container_name: cli
        build: api
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        depends_on:
            - mongodb
        networks:
            - mtlk-network


    mongodb:
        image: mongo:8.0.0
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
            - ./bin/mongo-init:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - mtlk-network

networks:
    mtlk-network:
        driver: bridge

volumes:
    mongo_data:
    kafka-data:
